### ISSUE TITLE
Selfhosted Solution Unable to Connect to NGINX

### ISSUE THREAD

**Issue by F1zzyD** [scribble-rs/scribble.rs#349]
Step one: Converted Docker run to Docker Compose file
Step two: Edited ports to fit my needs
Step three: Added entry into NGINX [per this page](https://github.com/scribble-rs/scribble.rs/wiki/reverse-proxy-(nginx))
Step four: Connection is never established or is able to connect.
Step five: Scrap the idea since it doesn't work.

Here is what I used as a compose file:
```
services:
    scribble.rs:
        pull_policy: always
        environment:
            - PORT=6343
        ports:
            - 6343:8080
        image: biosmarcel/scribble.rs:latest
```

**Comment by Bios-Marcel** [comment]
Hey, sadly I can't help you, as I don't use ngnix myself.

However, I am not sure the docker compose file is correct? shouldn't the inner port be on the right?

```yaml
services:
    scribble.rs:
        pull_policy: always
        environment:
            - PORT=6343
        ports:
            - 8080:6343
        image: biosmarcel/scribble.rs:latest
```

You could test on your machine, whether the server can be reached at all by sending some dummy request:

```
curl http://localhost:8080/v1/stats
```
